/*
 * sns-app
 *
 * SNSアプリ
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"log"
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetUserByHandleName - Get User Info
func GetUserByHandleName(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostUser - Create User
func PostUser(c *gin.Context) {
	var user Users
	if err := c.ShouldBindJSON(&user); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	if Db != nil {
		log.Printf("not nil")
	} else {
		log.Printf("nil")
	}
	result := Db.Create(&user)
	if result.Error != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": result.Error.Error()})
		return
	}

	c.JSON(http.StatusOK, user)
}
