/*
 * sns-app
 *
 * SNSアプリ
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetUserByHandleName - Get User Info
func GetUserByHandleName(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostUser - Create User
func PostUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
