/*
 * sns-app
 *
 * SNSアプリ
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Users struct {

	Id *interface{} `json:"id"`

	HandleName *interface{} `json:"handle_name"`

	DisplayName *interface{} `json:"display_name"`

	EncryptedEmailAddress *interface{} `json:"encrypted_email_address"`

	EncryptedPassword *interface{} `json:"encrypted_password"`
}
