version: '3.9'
services:
  db:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - type: bind
        source: ./db/postgres
        target: /var/lib/postgresql/data
      - type: bind
        source: ./db/logs
        target: /var/log
    networks:
      - sns_app
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - type: bind
        source: "./backend"
        target: "/app/backend"
      - type: bind
        source: "./.env"
        target: "/app/.env"
    depends_on:
      db:
        condition: service_started
    networks:
      - sns_app
networks:
  sns_app: