version: '3.9'

services:
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.utf8
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log