version: '3.9'

services:
  db:
    image: postgres:15
    ports:
      - "${POSTGRES_PORT}:3306"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER