/*
 * sns-app
 *
 * SNSアプリ
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	// WARNING!
	// Pass --git-repo-id and --git-user-id properties when generating the code
	//
	sw "backend/go"
)

func main() {
	log.Printf("Server started")

	sw.Init()

	router := sw.NewRouter()

	defer log.Fatal(router.Run(":8080"))
}
