// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AllError interface {
	IsAllError()
}

type UserPayload interface {
	IsUserPayload()
	GetUser() *User
	GetErrors() []AllError
}

type CommonPageInfo struct {
	TotalCount      int  `json:"totalCount"`
	HasNextPage     bool `json:"hasNextPage"`
	HasPreviousPage bool `json:"hasPreviousPage"`
}

type ConnectionInput struct {
	First  *int    `json:"first,omitempty"`
	After  *string `json:"after,omitempty"`
	Last   *int    `json:"last,omitempty"`
	Before *string `json:"before,omitempty"`
	Limit  *int    `json:"limit,omitempty"`
}

type CreatePostInput struct {
	ID      string `json:"id" validate:"len=36"`
	Content string `json:"content" validate:"min=1,max=400"`
}

type CreatePostPayload struct {
	User   *Post      `json:"user"`
	Errors []AllError `json:"errors,omitempty"`
}

type CreateUserInput struct {
	UserName   string  `json:"user_name" validate:"min=1,max=30"`
	ScreenName *string `json:"screen_name,omitempty" validate:"min=3,max=15"`
}

type CreateUserPayload struct {
	User   *User      `json:"user,omitempty"`
	Errors []AllError `json:"errors,omitempty"`
}

type DeletePostInput struct {
	ID string `json:"id" validate:"len=36"`
}

type DeletePostPayload struct {
	Success bool       `json:"success"`
	Errors  []AllError `json:"errors"`
}

type DeleteUserPayload struct {
	Success bool       `json:"success"`
	Errors  []AllError `json:"errors,omitempty"`
}

type Error struct {
	Message string `json:"message"`
}

func (Error) IsAllError() {}

type ModelInputID struct {
	ID string `json:"id"`
}

type Post struct {
	ID        string    `json:"id" validate:"len=36"`
	Content   string    `json:"content" validate:"min=1,max=400"`
	Author    *User     `json:"author"`
	Likes     []*User   `json:"likes"`
	Retweets  []*User   `json:"retweets"`
	CreatedAt time.Time `json:"created_at"`
}

type UpdatePostInput struct {
	ID      string `json:"id" validate:"len=36"`
	Content string `json:"content" validate:"min=1,max=400"`
}

type UpdatePostPaylod struct {
	User   *Post      `json:"user"`
	Errors []AllError `json:"errors,omitempty"`
}

type UpdateUserInput struct {
	UserName   *string `json:"user_name,omitempty" validate:"min=1,max=30"`
	ScreenName *string `json:"screen_name,omitempty" validate:"min=3,max=15"`
}

type UpdateUserPayload struct {
	User   *User      `json:"user,omitempty"`
	Errors []AllError `json:"errors,omitempty"`
}

type User struct {
	ID         string  `json:"id"`
	UserName   string  `json:"user_name" validate:"min=1,max=30"`
	ScreenName string  `json:"screen_name"`
	Posts      []*Post `json:"posts"`
	Followers  []*User `json:"followers"`
	Followings []*User `json:"followings"`
}

type GetPostPayload struct {
	Post     *Post           `json:"post,omitempty"`
	PageInfo *CommonPageInfo `json:"pageInfo"`
}

type GetPostsPayload struct {
	Posts    []*Post         `json:"posts,omitempty"`
	PageInfo *CommonPageInfo `json:"pageInfo"`
}

type GetUserPayload struct {
	User     *User           `json:"user,omitempty"`
	PageInfo *CommonPageInfo `json:"pageInfo"`
}

type GetUsersPayload struct {
	Users    []*User         `json:"users"`
	PageInfo *CommonPageInfo `json:"pageInfo"`
}
